### ISSUE TITLE
Coordinates data red when there's nothing to review 

### ISSUE THREAD

**Issue by elizawe** [humanitiesplusdesign/palladio#123] opened 2016-01-19 21:52 UTC
The dot disappears after the edit dimension window has been opened

**Comment by esjewett** [comment] 2016-01-19 22:47
Note to self: I believe this issue would be addressed by manually getting rid of the dot as described, downloading a new save file, and using that new save file to replace the sample.json file. The issue is due to a minor incompatibility between the old and and new save file formats.

**Closed** 2016-01-20 15:53 UTC
Labels: bug
