### ISSUE TITLE
Deleting a table (and adding another 

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#39] opened 2015-09-03 23:38 UTC

**Comment by cncoleman** [comment] 2015-09-03 23:40
Deleted Places, modified the data outside of Palladio and re-loaded. New data table will not "extend" and is not available to views. A complete re-install of tables seems to be the only solution.

**Comment by esjewett** [comment] 2015-09-04 15:42
Ok, I can recreate this. I'm sure I've tried before and been unable to figure out how. Pretty good idea what the problem is.

**Comment by esjewett** [comment] 2015-09-04 17:34
I believe now fixed on master.

**Closed** 2015-09-04 17:34 UTC
Labels: bug

**Comment by cncoleman** [comment] 2015-09-04 17:48
Great. I'll test it.
